#!/bin/bash

source project-common

while getopts h opt; do
	
	case $opt in
		
		h)
			echo 'Usage: '"$0"' <function name>'
			echo 'Must be in project source tree'
			echo 'Must be in module'
			exit 0
			;;
		
		*)
			echo 'Unrecognized option: '"$opt"
			exit 1
			;;
		
	esac
	
done

shift $[ $OPTIND - 1 ]

src-check

mod-check

downcasename=`downcase <<< $1`
prefix=`get-prefix`
funcname=`sed -e 's~_.*~~' <<< $prefix | downcase``sed -e 's~^[^_]*~~' <<< $prefix`'_'"$1"
upcasefuncname=`upcase <<< $funcname`

echo -n \
'static inline
/* ret */ '"$funcname"' (/* args */) {
#ifndef NDEBUG
	fprintf (stderr, "'"$funcname"' ();\n", /* arg names */);
#endif /* NDEBUG */
	
	/* code */
	
}
' > $downcasename.h
