#!/bin/bash

source project-common

while getopts h opt; do
	
	case $opt in
		
		h)
			echo 'Usage: '"$0"' <header library name>'
			echo 'Must be in project source tree'
			exit 0
			;;
		
		*)
			echo 'Unrecognized option: '"$opt"
			exit 1
			;;
		
	esac
	
done

shift $[ $OPTIND - 1 ]

src-check

add-module $1

downcasename="$(downcase <<< $1)"

cd $downcasename
source project-common

upcaseprefix="$(get-prefix | upcase)"

echo -n \
'#ifndef '"$upcaseprefix"'
# define '"$upcaseprefix"'

# ifndef NDEBUG
#  include <stdio.h>
# endif /* NDEBUG */

# include "'"$downcasename"'/internal.h"

#endif /* '"$upcaseprefix"' */
' > ../$downcasename.h

echo -n \
'internal.h
' > .ignore

write-makefile -h $1
