#!/bin/bash

source project-common

while getopts h opt; do
	
	case $opt in
		
		h)
			echo 'Usage: '"$0"' <module name>'
			exit 0
			;;
		
		*)
			echo 'Unrecognized option: '"$opt"
			exit 1
			;;
		
	esac
	
done

shift $[ $OPTIND - 1 ]

src-check

downcasename=`downcase <<< $1`

mkdir -p $downcasename
echo $1 > $downcasename/.module
