#!/bin/bash

source project-common

while getopts h opt; do
	
	case $opt in
		
		h)
			echo 'Usage: '"$0"' <executable name>'
			echo 'Must be in project source tree'
			exit 0
			;;
		
		*)
			echo 'Unrecognized option: '"$opt"
			exit 1;
			;;
		
	esac
	
done

shift $[ $OPTIND - 1 ]

src-check

add-module $1

downcasename=`downcase <<< $1`

cd $downcasename
source project-common

echo -n \
'#ifndef NDEBUG
# include <stdio.h>
#endif /* NDEBUG */

#include "internal.h"

int main (int argc, char** argv) {
	
	/* code */
	
}
' > main.c

echo -n \
'internal.h
' > .ignore

write-makefile -e $1
