#!/bin/bash

while getopts h opt; do
	
	case $opt in
		
		h)
			echo 'Usage: '"$0"' <project name>'
			exit 0
			;;
		
		*)
			echo 'Unrecognized option: '"$opt"
			exit 1
			;;
		
	esac
	
done

shift $[ $OPTIND - 1 ]

mkdir -p "$1"/build
mkdir -p "$1"/src
mkdir -p "$1"/lib
mkdir -p "$1"/bin
mkdir -p "$1"/inc
mkdir -p "$1"/notes
mkdir -p "$1"/doc

echo -n \
'SHELL = /bin/sh

incdir = ../inc
srcdir = ../src
bindir = ../bin
libdir = ../lib

CCFLAGS = -Wall -Werror -pipe -I $(incdir)
CLFLAGS = -L $(libdir)

modmkfiles = $(shell find $(srcdir) -type f -name .makefile)
moddirs = $(modmkfiles:$(srcdir)/%/.makefile=%)
modules = $(subst /,,$(moddirs))
modcfgs = $(modules:%=%configure)
modcleans = $(modules:%=%clean)
modclobbers = $(modules:%=%clobber)
modinstalls = $(modules:%=%install)
moduninstalls = $(modules:%=%uninstall)

include $(modmkfiles)

.DEFAULT_GOAL : all

.PHONY : all
all : $(modules)

.PHONY : configure
configure : $(modcfgs)

.PHONY : clean
clean : $(modcleans)

.PHONY : clobber
clobber : clean $(modclobbers)

.PHONY : install
install : $(modinstalls)

.PHONY : uninstall
uninstall : $(moduninstalls)
' > "$1"/build/Makefile

echo -n \
'export PATH=$PATH:'"$PWD"'/'"$1"'/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'"$PWD"'/'"$1"'/lib
export CPATH=$CPATH:'"$PWD"'/'"$1"'/inc

$(cat projrefs | sed -e 's~\(.*\)~source \1/bashrc')

export PROJ='"$PWD"'
' > "$1"/bashrc

touch projrefs
